version: '3'
services:

  db_postgres:
    image: postgres:14
    container_name: postgres_db_container
    restart: always
    ports:
        - "5432:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: "db_user"
        POSTGRES_PASSWORD: "db_pass"
        POSTGRES_DB: "school"