from .crud_teacher import teacher
from .crud_group import group
from .crud_student import student
from .crud_schedule import schedule
from .crud_room import room
from .crud_subject import subject
from .crud_week import week
from .crud_week_number import week_number
from .crud_lesson_time import lesson_time
from .crud_student_marks import student_mark
