"""init DB

Revision ID: a5727d3f0c20
Revises: 
Create Date: 2023-01-13 11:59:53.465417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5727d3f0c20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessontime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_lessontime_id'), 'lessontime', ['id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('available', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Integer(), nullable=False),
    sa.Column('average_mark', sa.DECIMAL(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('home_phone', sa.String(length=256), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('ix_student_middle_name'), 'student', ['middle_name'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Integer(), nullable=False),
    sa.Column('start_work', sa.Integer(), nullable=True),
    sa.Column('end_work', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('home_phone', sa.String(length=256), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_table('week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weeknumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_ts')
    )
    op.create_index(op.f('ix_weeknumber_number'), 'weeknumber', ['number'], unique=True)
    op.create_table('group_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_group__id'), 'group_', ['id'], unique=False)
    op.create_table('group2student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'student_id', name='unique_gs')
    )
    op.create_index(op.f('ix_group2student_id'), 'group2student', ['id'], unique=False)
    op.create_table('group2teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'teacher_id', name='unique_gt')
    )
    op.create_index(op.f('ix_group2teacher_id'), 'group2teacher', ['id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('created_ts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['week.day_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group_.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['lessontime.id'], ),
    sa.ForeignKeyConstraint(['week_number'], ['weeknumber.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_id', 'time_id', name='unique_schedule')
    )
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_group2teacher_id'), table_name='group2teacher')
    op.drop_table('group2teacher')
    op.drop_index(op.f('ix_group2student_id'), table_name='group2student')
    op.drop_table('group2student')
    op.drop_index(op.f('ix_group__id'), table_name='group_')
    op.drop_table('group_')
    op.drop_index(op.f('ix_weeknumber_number'), table_name='weeknumber')
    op.drop_table('weeknumber')
    op.drop_table('week')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_student_middle_name'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_lessontime_id'), table_name='lessontime')
    op.drop_table('lessontime')
    # ### end Alembic commands ###
